import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import subjectsRouter from "./subjects";
import chaptersRouter from "./chapters";
import topicsRouter from "./topics";
import examsRouter from "./exams";
import questionsRouter from "./questions";
import notesRouter from "./notes";
import pomodoroRouter from "./pomodoro";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import leaderboardRouter from "./leaderboard";
import externalTestsRouter from "./external-tests";
import notificationsRouter from "./notifications";
import qrScansRouter from "./qr-scans";
import seedRouter from "./seed";

const router: IRouter = Router();

router.use(healthRouter);
router.use(seedRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(subjectsRouter);
router.use(chaptersRouter);
router.use(topicsRouter);
router.use(examsRouter);
router.use(questionsRouter);
router.use(notesRouter);
router.use(pomodoroRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(adminRouter);
router.use(leaderboardRouter);
router.use(externalTestsRouter);
router.use(notificationsRouter);
router.use(qrScansRouter);

export default router;
